version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: covid-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: covid_corona_db_DP_YI
      MYSQL_USER: coviduser
      MYSQL_PASSWORD: covidpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-data:
